<a href="https://colab.research.google.com/github/jaskiratbudhmaan-ship-it/LocalRepo/blob/main/PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Introduction to pandas
# creation of dataframes
import pandas as pd
data = {"name":["john","Peter","lisa"],
        "age":[25,28,31],
         "salary":[300000,45000,25000]}
df = pd.DataFrame(data)
print(df)

    name  age  salary
0   john   25  300000
1  Peter   28   45000
2   lisa   31   25000

In [ ]:
df.describe()

        age         salary
count   3.0       3.000000
mean   28.0  123333.333333
std     3.0  153324.275095
min    25.0   25000.000000
25%    26.5   35000.000000
50%    28.0   45000.000000
75%    29.5  172500.000000
max    31.0  300000.000000

In [ ]:
# if we want to work with a csv r excel file
data = pd.read_csv("path of the file along with name")
# for excel files
data = pd.read_excel("expense4.xlxs")

In [ ]:
# exploring data in pandas
data = pd.read_excel("expeneses4.xlxs")
print(data.head(10)) # default value --> 5
print(data.tail(10)) # gives last 10 values from the data set whereas head gives first 10 values of the dataset

In [ ]:
print(data.info()) --> gives all information abt the values stored in the table

AttributeError: 'dict' object has no attribute 'info'

In [ ]:
print(data.describe()) # performs all statistical operations on numerical columns
print(data.isnull().sum())

In [ ]:
print(df.isnull().sum())

name      0
age       0
salary    0
dtype: int64

In [ ]:
df.head()

    name  age  salary
0   john   25  300000
1  Peter   28   45000
2   lisa   31   25000

# HANDLING DUPLICATE VALUES

In [ ]:
# Handling duplicate values

data = pd.read_excel("company.xlsx")

In [ ]:
print(data)

  Table 1 Unnamed: 1 Unnamed: 2 Unnamed: 3
0    EEID       NAME     GENDER     SALARY
1   EMP01     ayushi          F        NaN
2   EMP02      rohit          M      25000
3   EMP03   pranjali        NaN      27000
4   EMP01     ayushi          F      20000
5   EMP05        NaN          M      25000
6   EMP06      rohit          M        NaN

In [ ]:
data = pd.read_csv("company.csv")

In [ ]:
print(data)

    EEID      NAME GENDER   SALARY
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN

In [ ]:
print(data.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [ ]:
print(data["EEID"].duplicated().sum())

1

In [ ]:
print(data.drop_duplicates("EEID")) # ALWAYS DROP PRIMARY KEY

    EEID      NAME GENDER   SALARY
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN

# WORKING WITH MISSING DATA

In [ ]:
print(data.isnull().sum()) # nan --> not a number

EEID      0
NAME      1
GENDER    1
SALARY    2
dtype: int64

In [ ]:
print(data.isnull()) # tells how many values are null

    EEID   NAME  GENDER  SALARY
0  False  False   False    True
1  False  False   False   False
2  False  False    True   False
3  False  False   False   False
4  False   True   False   False
5  False  False   False    True

In [ ]:
print(data.dropna()) # to delete all null values

    EEID    NAME GENDER   SALARY
1  EMP02   rohit      M  25000.0
3  EMP01  ayushi      F  20000.0

In [ ]:
import numpy as np
# print(data.replace(np.nan,30000))

In [ ]:
data["SALARY"] = data["SALARY"].replace(np.nan,30000)

In [ ]:
print(data)

    EEID      NAME GENDER   SALARY
0  EMP01    ayushi      F  30000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  30000.0

In [ ]:
print(data)

  Table 1 Unnamed: 1 Unnamed: 2 Unnamed: 3
0    EEID       NAME     GENDER     SALARY
1   EMP01     ayushi          F        NaN
2   EMP02      rohit          M      25000
3   EMP03   pranjali        NaN      27000
4   EMP01     ayushi          F      20000
5   EMP05        NaN          M      25000
6   EMP06      rohit          M        NaN

In [ ]:
print(data.columns)

Index(['Table 1', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3'], dtype='object')

In [ ]:
print(data["SALARY"].mean())

24250.0

In [ ]:
data["SALARY"] = data["SALARY"].replace(np.nan,24250.0)

In [ ]:
print(data)

    EEID      NAME GENDER   SALARY
0  EMP01    ayushi      F  24250.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  24250.0

In [ ]:
#forward fill and backward fill
print(data.fillna(method = "bfill")) #bilateral fill or backward fill

    EEID      NAME GENDER   SALARY
0  EMP01    ayushi      F  24250.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      F  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05     rohit      M  25000.0
5  EMP06     rohit      M  24250.0

/tmp/ipykernel_1367/2643927631.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(data.fillna(method = "bfill"))

In [ ]:
print(data.fillna(method = "ffill")) #forward fill

    EEID      NAME GENDER   SALARY
0  EMP01    ayushi      F  24250.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      M  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05    ayushi      M  25000.0
5  EMP06     rohit      M  24250.0

/tmp/ipykernel_1367/1391920301.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(data.fillna(method = "ffill"))

In [ ]:
# we ca also use fillna in place of replace

# COLUMN TRANSFORMATION PANDAS

In [ ]:
import pandas as pd
data = pd.read_excel("ESD.xlxs")
print(data)

In [ ]:
data.loc[(data["Bonus %"]==0),"getsbonus"] = "no bonus"
data.loc([data["Bonus %"]>0,"getsbonus"]) = "bonus"

In [ ]:
data = pd.read_excel("practice_1.xlsx")
print(data)
data["full name"] = data["firstname"].str.capaitalize()+" "+ data["lastname"].str.capitalize()

In [ ]:
data["bonus"] = (data["salary"]/100)*20

In [ ]:
data = { "months":["january","february","march","april"]}
a = pd.DataFrame(data)

In [ ]:
def extract(value):
  return value[0:3]

In [ ]:
a["Short_Months"] = a["months"].map(extract)

In [ ]:
print(a)

     months Short_Months
0   january          jan
1  february          feb
2     march          mar
3     april          apr

# Group BY IN PANDAS

In [ ]:
data = pd.read_excel("ESD.xlxs")
gp = data.groupby(["department","gender"]).add({"EEID":"count"})

In [ ]:
gp1 = data.groupby(["country","gender"]).agg({"age":"mean"})

# MERGE JOIN AND CONCATENATE IN PANDAS

In [ ]:
import pandas as pd

In [ ]:
data1 = {
    "empid" :["e01","e02","e03","e04","e05","e06"],
    "names" :["ram","sham","rahul","vishal","ravi","john"],
    "age"   :[34,56,23,44,32,36]
}
data2 = {
    "empid" :["e01","e07","e03","e04","e08","e06"],
    "salary" :[45000,56000,34000,20000,50000,62000]
}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [ ]:
df1

  empid   names  age
0   e01     ram   34
1   e02    sham   56
2   e03   rahul   23
3   e04  vishal   44
4   e05    ravi   32
5   e06    john   36

In [ ]:
df2

  empid  salary
0   e01   45000
1   e02   56000
2   e03   34000
3   e04   20000
4   e05   50000
5   e06   62000

In [ ]:
#MERGE
print(pd.merge(df1,df2,on = "empid", how = "inner")) #inner default

  empid   names  age  salary
0   e01     ram   34   45000
1   e03   rahul   23   34000
2   e04  vishal   44   20000
3   e06    john   36   62000

In [ ]:
print(pd.merge(df1,df2,on = "empid", how = "left"))

  empid   names  age   salary
0   e01     ram   34  45000.0
1   e02    sham   56      NaN
2   e03   rahul   23  34000.0
3   e04  vishal   44  20000.0
4   e05    ravi   32      NaN
5   e06    john   36  62000.0

In [ ]:
print(pd.merge(df1,df2,on = "empid", how = "right"))

  empid   names   age  salary
0   e01     ram  34.0   45000
1   e07     NaN   NaN   56000
2   e03   rahul  23.0   34000
3   e04  vishal  44.0   20000
4   e08     NaN   NaN   50000
5   e06    john  36.0   62000

In [ ]:
data1 = {
    "empid" :["e01","e02","e03","e04","e05","e06"],
    "names" :["ram","sham","rahul","vishal","ravi","john"],
    "age"   :[34,56,23,44,32,36]}

data2 = {
    "empid" :["e07","e08","e09","e010","e011","e012"],
    "names" :["ben","nick","james","sevii","tabi","vish"],
    "age"   :[34,56,23,44,32,36]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [ ]:
print(pd.concat([df1,df2]))

  empid   names  age
0   e01     ram   34
1   e02    sham   56
2   e03   rahul   23
3   e04  vishal   44
4   e05    ravi   32
5   e06    john   36
0   e07     ben   34
1   e08    nick   56
2   e09   james   23
3  e010   sevii   44
4  e011    tabi   32
5  e012    vish   36

# Compare DataFrames

In [ ]:
dict = {"Fruits":["mango","apples","banana","papaaya"],
        "price":[100,150,50,35],
        "quantity":[15,10,10,3]}
df = pd.DataFrame(dict)

In [ ]:
df

    Fruits  price  quantity
0    mango    100        15
1   apples    150        10
2   banana     50        10
3  papaaya     35         3

In [ ]:
df2 = df.copy()
df2.loc[0,"price"] = 120
df2.loc[1,"price"] = 175
df2.loc[3,"price"] = 30
df2.loc[0,"quantity"] = 12
df2.loc[1,"quantity"] = 15
df2.loc[3,"quantity"] = 5

In [ ]:
print(df2)

    Fruits  price  quantity
0    mango    120        12
1   apples    175        15
2   banana     50        10
3  papaaya     30         5

In [ ]:
print(df.compare(df2)) #compare

   price        quantity
    self  other     self other
0  100.0  120.0     15.0  12.0
1  150.0  175.0     10.0  15.0
3   35.0   30.0      3.0   5.0

In [ ]:
print(df.compare(df2,align_axis=0)) # default axis = 1

         price  quantity
0 self   100.0      15.0
  other  120.0      12.0
1 self   150.0      10.0
  other  175.0      15.0
3 self    35.0       3.0
  other   30.0       5.0

In [ ]:
print(df.compare(df2,keep_equal=True))

  price       quantity
   self other     self other
0   100   120       15    12
1   150   175       10    15
3    35    30        3     5

In [ ]:
print(df.compare(df2,keep_shape=True))

  Fruits        price        quantity
    self other   self  other     self other
0    NaN   NaN  100.0  120.0     15.0  12.0
1    NaN   NaN  150.0  175.0     10.0  15.0
2    NaN   NaN    NaN    NaN      NaN   NaN
3    NaN   NaN   35.0   30.0      3.0   5.0

#Pivoting and melting dataframes

In [ ]:
dict = {"keys":["k1","k2","k1","k2"],
        "names":["john","ben","david","peter"],
        "house" :["red","blue","green","red"],
        "grades" :[3,8,9,8]
        }
df = pd.DataFrame(dict)

In [ ]:
df

  keys  names  house
0   k1   john    red
1   k2    ben   blue
2   k1  david  green
3   k2  peter    red

In [ ]:
print(df.pivot(index="keys", columns="names", values="house"))

names   ben  david john peter
keys
k1      NaN  green  red   NaN
k2     blue    NaN  NaN   red

In [ ]:
print(df.pivot(index="keys", columns="names", values=["house", "grades"]))

      house                   grades
names   ben  david john peter    ben david john peter
keys
k1      NaN  green  red   NaN    NaN     9    3   NaN
k2     blue    NaN  NaN   red      8   NaN  NaN     8

#Melting

In [ ]:
import pandas as pd
dict = {"names":["john","ben","david","peter"],
        "house" :["red","blue","green","red"],
        "grades" :[3,8,9,8]
        }
df = pd.DataFrame(dict)

In [ ]:
print(pd.melt(df,id_vars= ["names"],value_vars=["house","grades"],var_name="houses & grades",value_name="values"))

   names houses & grades values
0   john           house    red
1    ben           house   blue
2  david           house  green
3  peter           house    red
4   john          grades      3
5    ben          grades      8
6  david          grades      9
7  peter          grades      8